### PR TITLE
Stream forward kinematics data and fetch it in the client device

### LINKED ISSUE #102: CartesianControlServer stream FK
CartesianControlServer stream FK

### PR DESCRIPTION
**Pull request by PeterBowman**
Resolves #102. Marking as work in progress: needs proper testing (preferably with high-frequency, streaming commands) so that we make sure there are no race conditions caused by concurrent access.

A few design decisions were inspired by YARP's remote_controlboard & controlboardwrapper2 devices. It's worth noting that this pair sends/receives timestamp envelopes along with actual data (e.g. encoder values, control mode, etc.). In the future, we could take advantage of this technique to provide a more accurate way of describing cartesian position and current motion status.

### CODE REVIEW

**Comment by jgvictores** [comment]
Added the `status: in progress` and `testing required` labels. :-)
Please correct if incorrectly interpreted!

**Comment by PeterBowman** [comment]
The following was printed to stdout during a test run with `keyboardController`.

```
yarp: BottleImpl reader failed, unrecognized object code 0
yarp: *** Multicast/UDP packet dropped - checksum error ***
yarp: The UDP/MCAST system buffer limit on your system is low.
yarp: You may get packet loss under heavy conditions.
yarp: To change the buffer limit on linux: sysctl -w net.core.rmem_max=8388608
yarp: (Might be something like: sudo /sbin/sysctl -w net.core.rmem_max=8388608)
yarp: *** 1 datagram packet(s) dropped - checksum error ***
```

**Comment by PeterBowman** [comment]
> The following was printed to stdout (...)

This error shows up in the process that launches the client device. It may take some time to print the first `BottleImpl reader failed` line. I tested the client against pending read operations (by calling `yarp::os::BufferedPort<T>::getPendingReads()` every few milliseconds) in case the missing packages originated from here, but to no avail - it remains at 0 almost all the time.

Interesting: the transition from `Port` to `BufferedPort` at cf55dd6  caused the CCS to print all state messages in a row when queried via `yarp read ... /CCS_port_name/state:o`. Previously, they looked like this (ASIBOT):

```
~$ yarp read ... /asibotSim/BasicCartesianControl/state:o
yarp: Port /tmp/port/1 active at tcp://192.168.2.12:10021/
yarp: Receiving input from /asibotSim/BasicCartesianControl/state:o to /tmp/port/1 using tcp
0.0 0.0 1.4 0.0 0.0 0.0
0.0 0.0 1.4 0.0 0.0 0.0
0.0 0.0 1.4 0.0 0.0 0.0
0.0 0.0 1.4 0.0 0.0 0.0
[...]
```

Anyway, YARP's ControlBoardWrapper uses `BufferedPort` as well, newlines get inserted between consecutive bottles.

It's debugging time!

**Comment by PeterBowman** [comment]
> Interesting: the transition from Port to BufferedPort at cf55dd6 caused the CCS to print all state messages in a row (...)

Of course it did, I forgot to clear the FK status bottle and messages were being appended, causing overflows at some point. Fixed at 12945a8.

**Comment by PeterBowman** [comment]
Regarding concurrency issues in the cartesian controller (I'll focus on `BasicCartesianControl` for now), three elements have to be considered:

* concurrent access to the remote controlboard via motor interface handles (e.g. `IEncoders`, `IPositionControl`, etc.): no locks, but the implementation of `remote_controlboard` should be thread-safe :ok_hand:
* concurrent access to the solver via handle of type `ICartesianSolver`: no locks, but both `KdlSolver` and `AsibotSolver` now create copies of shared objects, so we should be on the safe end again :ok_hand:
* multi-threading within the controller itself (e.g. `RateThread`): current locks cover the state identifier (`getCurrentState`, `setCurrentState`), but some other members are shared between threads without mutex guards (e.g. desired cartesian velocities and forces); by now, we could assume that issuing multiple commands simultaneously is not allowed and re-think the internal behavior in #118 :question:

@jgvictores removing WIP labels, PR ready for code review.

**Review by jgvictores — APPROVED** [review]
Looks good to me!

**Comment by jgvictores** [comment]
@PeterBowman Merged! Feel free to delete branches and close issues, I'm sure you have kept much better track of the components involved.

**Comment by PeterBowman** [comment]
Thanks! @jgvictores @RaulFdzbis you may want to take a look at `icra2018`, which was based on the now deleted `issue201fkStream`. The last of its two commits (e2bfa1c) was partially merged into develop at a96c5e6, see comments. If you want to re-use it, please [cherry-pick](https://git-scm.com/docs/git-cherry-pick).

**Comment by jgvictores** [comment]
Commited hot-fix at 093594cfedf7e0a6545201c362c96e033f1b3a1a, deleted `icra2018`.

**Comment by PeterBowman** [comment]
> concurrent access to the solver via handle of type `ICartesianSolver`: no locks, but both `KdlSolver` and `AsibotSolver` now create copies of shared objects, so we should be on the safe end again ok_hand

Just a follow-up: I have repurposed this part so that all access to shared resources is kept behind a mutex. Turns out that KDL solver instances store a reference to the kinematic chain, therefore I'm no longer creating copies of it nor instantiating the solvers each time a FK/IK/ID is performed. Instead, these are created upon device configuration and updated accordingly (see `KDL::SolverI::updateInternalDataStructures`) whenever the chain is altered, i.e. upon tool change.

See https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/895166548a82efacfc893126f4109863f341025a (especially: https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/14a47ab8cef6b0e52274e52c1a3de9a58b95bfd4).

**Pull request merged**
