### PR TITLE
Twolimbcc

### PR DESCRIPTION
**Pull request by munozyanez**
Completed all tasks. Working both limbs and revised DH for both legs.
@jgvictores , remember you hardcoded the robot name as "teoSim", so check it properly to avoid problems.
Movement is still not fine, but it will be an issue in new repo.

### CODE REVIEW

**Comment by jgvictores** [comment]
@munozyanez Thanks, looking much better. Could you please review and resolve the merge conflicts to enable the automatic merge?
Haven't checked the details, but hopefully it's just something to do with git submodules and all you have to do is force your version.

**Comment by munozyanez** [comment]
I can not say what to keep or not in teo-main/libraries/TeoYarp/CMakeLists.txt
Find attached difference text files
[CMakeLists_BACKUP_4303.txt](https://github.com/roboticslab-uc3m/teo-main/files/818660/CMakeLists_BACKUP_4303.txt)
[CMakeLists_BASE_4303.txt](https://github.com/roboticslab-uc3m/teo-main/files/818661/CMakeLists_BASE_4303.txt)
[CMakeLists_LOCAL_4303.txt](https://github.com/roboticslab-uc3m/teo-main/files/818663/CMakeLists_LOCAL_4303.txt)
[CMakeLists_REMOTE_4303.txt](https://github.com/roboticslab-uc3m/teo-main/files/818662/CMakeLists_REMOTE_4303.txt)

**Comment by PeterBowman** [comment]
@munozyanez I've merged `develop` into the derived branch `twolimbcc-merged`, please check if you are OK with these changes: 545a250. Most importantly, `BasicTwoLimbCartesianControl` and `TwoLimbCartesianControlServer` have been enabled as dynamically loaded plugins and their respective .ini files were included as well. Then, you just merge `twolimbcc-merged` into `twolimbcc` and the conflicts should be gone (not sure about gait and how submodules work, though).

BTW I can't compile this code with the checked out revision of gait (roboticslab-uc3m/gait@d0dbd6d). I'm getting a `'abs' is not a member of 'std'` error at line 437 in `src/tools/cpp`.

**Comment by jgvictores** [comment]
> BTW I can't compile this code with the checked out revision of gait (roboticslab-uc3m/gait@d0dbd6d). I'm getting a 'abs' is not a member of 'std' error at line 437 in src/tools/cpp

Touched at https://github.com/roboticslab-uc3m/gait/commit/6f717d9e2fd13124e20b5147b65136bae4ca0478

**Comment by jgvictores** [comment]
Version of `gait`used updated in https://github.com/roboticslab-uc3m/teo-main/commit/f10f7b7f63a70e70d70e7668cc7c7033f9f22c2a

**Comment by jgvictores** [comment]
Final merge at https://github.com/roboticslab-uc3m/teo-main/commit/94e6baa9066b04606807b691f27c8fb8bdf1bfaf

**Pull request merged**
